spring:
  application:
    name: l9g-app-iatk

  profiles:
    active: default

  config:
    import: optional:file:config.yaml

  main:
    banner-mode: OFF
    web-application-type: NONE

  shell:
    interactive:
      enabled: true
    command:
      version:
        enabled: true
    history:
      enabled: false
    help:
      enabled: true
      long-names: help
      short-names: h
      command: help

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger:%line - %yellow(%msg %n)"
  level:
    root: OFF
    org.jline: OFF

keycloak:
  base-url: "https://id.dev.sonia.de"
  realm: "*** undefined ***"
  client-id: "admin-cli"
  client-secret: "*** undefined ***"
  trust-all-certificates: true
